// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moment_04.Data;

#nullable disable

namespace Moment_04.Migrations
{
    [DbContext(typeof(SongContext))]
    [Migration("20240220182844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Moment_04.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Song_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Song_artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Song_genre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Song_length")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
